properties:
# ------------------------------------------------
  data: 
    mssql:
      host: mssql.chinchalinchin.com
      database: chinchalinchin
    logs:
      username: gmoore
      path: /var/log/
# ------------------------------------------------
  inventory:
    host:
      username: gmoore
    local:
      username: gmoore
      home: /Users/gmoore/
    k8s:
      host: https://localhost:6443
      username: gmoore
# ------------------------------------------------
  tools:
    artifactory:
      url: artifactory.chinchalinchin.com
    github:
      url: github.com/chinchalinchin
      groups: 
        chinchalinchin: /Users/gmoore/Home/lib/
    jenkins:
      url: jenkins.chinchalinchin.com