# -----------------------------------------------------------------------------------
# ----------------------------- VIEW CONFIGURATION ----------------------------------
# -----------------------------------------------------------------------------------
views:
  # ----------------------------- INVENTORY VIEWS
  inventory:
    # --- 1. HOST VIEWS
    host:
      certificates:
        # Command to present certificate context.
        cmd: ls -al /etc/gerberlife/SSL
      docker:
        # Commands to present Docker context.
        containers: sudo docker ps
        images: sudo docker images
        stats: sudo docker stats --no-stream
      specifications:
        # Commands to present host context.
        os: lsb_release -a
        cpu: lscpu
        memory: free
        processes: top -b -n 1 | head -n 17
    # --- 2. K8S VIEWS
      k8s:
        pods: {}
  # ----------------------------- DATA VIEWS
  data: 
    mssql:
      specifications:
        version: SELECT @@VERSION;
  # ----------------------------- TOOLS VIEWS
  tools:
    # --- 1. ARTIFACTORY VIEWS
    artifactory:
      latest: {}
    # --- 2. github VIEWS
    github:
      blobs:
        <key>:
          title: <title>
          files:
            <file-path>: <hint>
    # --- 2. JENKINS VIEWS
    jenkins:
      config: {}
      console: {}