task:
# ------------------------------------------------
  context: true
  system: true
# ------------------------------------------------
  ticket: 
    title: "<TITLE>"
    content: |
      <TASK>
    shell:
      - <cmd>
# ------------------------------------------------
  data:
    logs:
      parameters: {}
      views: {} 
      # -----------------------------------------
      # parameters:
      #   host: integ1.chinchalinchin
      #   app: java-app
      #   search:
      #     # --- APACHE LOG FORMAT
      #     # format: DD/Month/YYYY:HH:MM:SS
      #     # --- JAVA LOG FORMAT
      #     # format: YYYY-MM-DD HH:MM:SS
      #     # ------------------------
      #     # start: 14/Feb/2026:13:36:00
      #     # end: 14/Feb/2026:13:37:00
      #     start: '2026-02-15 11:20:00'
      #     end: '2026-02-15 11:21:00'
      # views:
      #   search: false
    mssql:
      parameters: {}
      views: {}
      # parameters:
      #   query: SELECT 1;
      # views:
      #   query: false
      #   specifications: false
    psql:
      parameters: {}
      views: {}
# ------------------------------------------------
  inventory:
    # -------------------------------------------
    host: []
    # host: 
      # - parameters:
      #     hostname: integ.chinchalinchin.com
      #     command: sudo docker ps
      #   views:
      #     certificates: false
      #     command: true
      #     docker: false
      #     specifications: false

    # -------------------------------------------
    k8s: []
    # k8s:
      # - parameters:
      #     namespace: devops
      #   views:
      #     pods: true
      # - parameters:
      #     namespace: monitoring
      #   views: 
      #     pods: true
# ------------------------------------------------
  tools:
    # -------------------------------------------
    artifactory: []
    # artifactory:
      # - parameters:
      #     repo: chinchalinchin
      #     artifact: java-app
      #   views:
      #     latest: true
    # -------------------------------------------
    github: []
    # github:
    #   - parameters:
    #       repo: golem
    #       group: chinchalinchin
    #     views:
    #       directory: true
    #       ai_doom_docs: true
    #       ai_doom_src: true
    # -------------------------------------------
    prometheus: []
    # prometheus:
      # - parameters:
      #     hostname: testing.chinchalinchin.com
      #     application: java-app
      #   views: 
      #     metrics: true
    # -------------------------------------------
    jenkins: []
    # jenkins:
      # - parameters:
      #     job: dxs-tasks
      #   views:
      #     config: false
      #     console: false
    # -------------------------------------------