# -----------------------------------------------------------------------------------
# ----------------------------- VIEW CONFIGURATION ----------------------------------
# -----------------------------------------------------------------------------------
# TODO: MACOS Spec Command: system_profiler SPHardwareDataType
views:
  # ----------------------------- INVENTORY VIEWS
  inventory:
    # --- 1. HOST VIEWS
    host:
      certificates:
        # Command to present certificate context.
        cmd: ls -al /etc/gerberlife/SSL
      docker:
        # Commands to present Docker context.
        containers: sudo docker ps
        images: sudo docker images
        stats: sudo docker stats --no-stream
      specifications:
        # Commands to present host context.
        os: lsb_release -a
        cpu: lscpu
        memory: free
        processes: top -b -n 1 | head -n 17
    # --- 2. K8S VIEWS
      k8s:
        pods: {}
  # ----------------------------- DATA VIEWS
  data: 
    mssql:
      specifications:
        version: SELECT @@VERSION;
  # ----------------------------- TOOLS VIEWS
  tools:
    # --- 1. ARTIFACTORY VIEWS
    artifactory:
      latest: {}
    # --- 2. DOCKERHUB VIEWS
    dockerhub: {}
    # --- 3. GITHUB VIEWS
    github:
      blobs:
        # -------------- DOCUMENTATION
        golem_board:
          title: Golem Task Board
          files:
            docs/board/roadmap.md: markdown
            docs/board/issues.md: markdown
        golem_docs:
          title: "Golem Documentation"
          files:
            README.md: markdown
            docs/configuration.md: markdown
        golem_theory:
          title: "Golem Documentation (Theory)"
          files:
            docs/philosophy.md: markdown
            docs/environment.md: markdown
            docs/brain.md: markdown
            docs/training.md: markdown
        # -------------- SOURCE CODE
        golem_config:
          title: "Golem Configuration & Utilities"
          files: 
            requirements.txt: text
            conf/app.yaml: yaml
            conf/simple.cfg: conf
            main.py: python
            app/utils/doom.py: python
        golem_pipeline:
          title: "Golem Pipeline Source Code"
          files:
            app/pipeline/analyze.py: python
            app/pipeline/intervene.py: python
            app/pipeline/record.py: python
            app/pipeline/run.py: python
            app/pipeline/train.py: python
        golem_model:
          title: "Golem Model Source Code"
          files: 
            app/models/config.py: python
            app/models/brain.py: python
            app/models/dataset.py: python
            app/models/loss.py: python
            app/utils/model.py: python
        golem_client:
          title: "Golem Client Source Code"
          files:
            docker-compose.yml: yaml
            Dockerfile.agent: dockerfile
            app/client/agent.py: python
            app/client/arena.py: python
            app/client/host.py: python
        # -------------- CONTINUOUS INTEGRATION
        golem_ci:
          title: "Golem Continuous Integration"
          files:
            .github/workflows/ci.yml: yaml
            Dockerfile.agent: dockerfile
            Dockerfile.ci: dockerfile
            tests/test_dataset.py: python
        golem_mkdocs:
          title: "Golem MkDocs Configuration"
          files:
            .github/workflows/ci.yml: yaml
            Dockerfile.ci: dockerfile
            mkdocs.yml: yaml
            docs.sh: bash
            docs/javascripts/mathjax.js: javascript
        # -------------- EVERYTHING ELSE
        golem_etc:
          title: "Golem ETC"
          files:
            app/client/__init__.py: python
            app/models/__init__.py: python
            app/pipeline/__init__.py: python
            app/pipeline/generate.py: python
            app/utils/conf.py: python
            app/templates/audit.j2: jinja2
            app/templates/inspect.j2: jinja2
            conf/basic.cfg: conf
            conf/classic.cfg: conf
            conf/fluid.cfg: conf
            docs/board/closed/issues.md: markdown
            docs/board/closed/phases.md: markdown
    # --- 4. JENKINS VIEWS
    jenkins:
      config: {}
      console: {}